version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    networks:
      - backend
    command: npm run start
    depends_on:
      - postgres
  postgres:
    container_name: postgresql-listen-app
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: listen_app
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - backend
    volumes:
      - ./db-data:/var/lib/postgresql/data

networks:
  backend: